spring.application.name=clubverse-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/clubverse
spring.datasource.username=postgres
spring.datasource.password=Rsha@1056#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true